volumes:
  postgres_data:
    name: pg_data
  
services:
  db:
    image: postgres:15
    container_name: delivery_db
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB}"
      PGPORT: "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data


